### ISSUE TITLE
Ubuntu 20.04 installation stops after /sbin/iptables -P OUTPUT DROP

### ISSUE THREAD

**Issue by AndrewW-GIT** [fwbuilder/fwbuilder#100]
When installing on Ubuntu 20.04, and running the .fw file.
The file reaches the command 
/sbin/iptables -P OUTPUT DROP

then the network drop and no further actions

**Comment by sirius** [comment]
Hey, @AndrewW-GIT. 

If I understand your problem correctly, this is a rule set issue - not a bug in fwbuilder. You should have some rules to allow ssh / established traffic before the `iptables -P OUTPUT DROP` rule.

See https://superuser.com/questions/738253/iptables-preventing-outgoing-packets as an inspiration.

If I have misunderstood - please do reopen the issue.
