### ISSUE TITLE
Fresh tag?

### ISSUE THREAD

**Issue by Thulium-Drake** [fwbuilder/fwbuilder#113]
Hi guys,

First of all, thanks a million for keeping this project alive!

But is it possible to make a fresh tag anytime soon? The last one is 2 years old by now and a lot of improvements have been made to the code in the mean time. (for instance, I can't build 5.3.7 on Debian 10 because qmake can't find what it's looking for, but the 6.0.0-beta does work)

Perhaps tag it as 5.4 (or 6.0.0 if you feel that's ready, as the beta is also over a year old by now)

**Comment by sirius** [comment]
Hello, @Thulium-Drake!

Yes, there will be a 6.0 release soon. As you might have seen, I've done some work the last few days - but as I'm the only one working on this I only have so much time. There's only one development task left in the [6.0 milestone](https://github.com/fwbuilder/fwbuilder/milestone/2). Having fixed the unit tests I'm more confident fixing bugs and adding some small new features - after 6.0 is released.

**Comment by Thulium-Drake** [comment]
Awesome! Good to hear!

**Comment by monotek** [comment]
I'll try to build new ubuntu packages too :)
Last on is a 5.3.7 version from 2017 too.
https://launchpad.net/~monotek/+archive/ubuntu/fwbuilder

I'll try to build a github action around it :)

**Comment by sirius** [comment]
https://github.com/fwbuilder/fwbuilder/releases/tag/v6.0.0-rc1
