### ISSUE TITLE
Could not find Fedora 24 spec file

### ISSUE THREAD

**Issue by roweryan** [fwbuilder/fwbuilder#12]
Here seems to be the best place to attach it for now. Hopefully it will get more people using the software. Until the released are ready it relies on zipping up the git tree from a directory called fwbuilder-5.3.6 and saving it to fwbuilder-5.3.6.zip

Maybe once the project is live again Fedora will pick it up. Anyway attached is the spec file, build with `rpmbuild -bb fwbuilder.spec`
[fwbuilder.spec.txt](https://github.com/fwbuilder/fwbuilder/files/439307/fwbuilder.spec.txt)

**Comment by didierm** [comment]
FYI : I packaged the most recent git (dcc919d) for Fedora 25, and made it available at [https://copr.fedorainfracloud.org/coprs/ifas/fwbuilder/](url).
