### ISSUE TITLE
Install Firewall on Ubuntu 16.04

### ISSUE THREAD

**Issue by jb-alvarado** [fwbuilder/fwbuilder#13]
Hello,
first of all thank you that you continue this great project! 

I use fwbuilder now since 1,5 year and for some weeks I upgrade ubuntu from 14.04 to 16.04. Since this time I am not able anymore to install the firewall over ssh under a different user. As root (with key) is no problem, but as specific user it doesn't work.

Any idea what is happen here?

Regards!
Jonathan

**Comment by a-schild** [comment]
Hello,

Am 12.09.2016 um 11:11 schrieb jb-alvarado:
>
> Hello,
> first of all thank you that you continue this great project!
>
> I use fwbuilder now since 1,5 year and for some weeks I upgrade ubuntu 
> from 14.04 to 16.04. Since this time I am not able anymore to install 
> the firewall over ssh under a different user. As root (with key) is no 
> problem, but as specific user it doesn't work.
>

Has the specific user write rights in the given directory?
What error message to you receive?

Can you ssh to the FW with the given user login data?

André

**Comment by jb-alvarado** [comment]
Hello André,
sorry, I was not so clear.

Copy the fw file and the firewall script to ubuntu works, only running the firewall script at the end doesn't work.

The log shows this:

Installation plan:
Copy file: /Users/jb_/fw-router.fw --> /etc/fw/fw-router.fw
Copy data file: fw-router.fwb --> /etc/fw/
Run script echo '--**--**--'; chmod +x /etc/fw/fw-router.fw; sudo -S /etc/fw/fw-router.fw && echo 'Policy activated'

```
Copying /Users/jb_/fw-router.fw -> ubuntu16:/etc/fw/fw-router.fw
Firewall Builder GUI 5.3.6-32-g0f214df-dirty
fwuser@ubuntu16's password:
SSH session terminated, exit status: 0
Copying fw-router.fwb -> ubuntu16:/etc/fw/
Firewall Builder GUI 5.3.6-32-g0f214df-dirty
fwadmin@ubuntu16's password:
SSH session terminated, exit status: 0
Firewall Builder GUI 5.3.6-32-g0f214df-dirty
fwadmin@ubuntu16's password:
--**--**--
Logged in
[sudo] Passwort für fwuser:
Connection to ubuntu16 closed.
SSH session terminated, exit status: 1
Firewall policy installation failed
```

Login with this user and run sudo fw-router.fw works to.

**Comment by monotek** [comment]
Do you use the newest version?
If you like you can use my Ubuntu PPA of this repo:
https://launchpad.net/~monotek/+archive/ubuntu/fwbuilder
No problems so far.

**Comment by jb-alvarado** [comment]
I have compile fwbuilder from git, under OSX. I used the old git location, but I think there was no changes. I could try to make a rebase and compile it again.

**Comment by sirius** [comment]
@jb-alvarado I'll try to have a 5.3.7-rc2 ready for you for [download](https://drive.google.com/drive/folders/0B4V9gxpLkC2AN1lub0hNMXdqTGc) tonight (CEST).

**Comment by jb-alvarado** [comment]
Ok, thank you! I will try it then.

**Comment by sirius** [comment]
@jb-alvarado Currenty no finished patches are affecting macOS for -rc2, so I compiled [5.3.7-rc1](https://drive.google.com/drive/folders/0B4V9gxpLkC2AM1M2UDZtdGcySnM) for macOS for you.

**Comment by monotek** [comment]
Would be nice these changes would also be pushed to the Github (dev?) repo so more people could test.

**Comment by sirius** [comment]
@monotek Sorry. The patches are cleaned up, pushed, and 5.3.7 is released.

**Comment by flakrat** [comment]
Howdy, Is there a 5.3.7 release build for OSX available somewhere? Thanks

**Comment by sirius** [comment]
@flakrat https://github.com/fwbuilder/fwbuilder/releases/tag/v5.3.7
