### ISSUE TITLE
NFLOG support

### ISSUE THREAD

**Issue by b4ssh** [fwbuilder/fwbuilder#15]
Hi there!

Are in your plans add NFLOG support?

Look at following announce:
-  The ipt_ULOG and ebt_ulog modules, and thus the ULOG targets for iptables and
-  ebtables, were removed in the 3.17 kernel. NFLOG replaces ULOG and works for
-  iptables, ip6tables and ebtables. If you are using the ULOG target in your
-  configuration, you will need to replace it with NFLOG for your configuration
-  to apply correctly under current kernels.
  +
-  You will also need to ensure NFLOG is enabled in the ulogd configuration.
-  This is enabled by default.

https://anonscm.debian.org/cgit/collab-maint/ulogd2.git/commit/?id=e20a0ed299793c40e345ecee46f234423574da0b

**Comment by nottledim** [comment]
For the truly impatient and in the traditional spirit of hacking I've created a patch which will replace ULOG targets with NFLOG in the output file.  Nothing in the UI is changed.  The patch affects just 

fwbuilder-master/src/iptlib/PolicyCompiler_PrintRule.cpp

It works for me, ymvv, hardly tested and no guarantees.

[nflog.patch.txt](https://github.com/fwbuilder/fwbuilder/files/775382/nflog.patch.txt)

**Comment by sirius** [comment]
@b4ssh NFLOG-support was added in 7d49ab96b2a2d45d69593fda64c9f32b60fcdd6b.
