### ISSUE TITLE
SSH connection issue with windows client

### ISSUE THREAD

**Issue by DrSh4d0w** [fwbuilder/fwbuilder#19]
Hello,
I will first adress you a realy great thanks for your courage an time.
I use FWbuilder since 2 years and this is an amazing soft :)

So here is my issue. ( this is certainely nothing btw )

I use the windows version ( 5.3.7-rc1 ) and when i'm trying to install rules on my firewall ( ubuntu 16.04 with openSSH_7.2p2 Ubuntu-4ubuntu2.1, openSSL 1.0.2g and just in case  4.4.0-59-generic ) i get the following : 

Summary:
* Running as user : **********
* Firewall name : firewall
* Installer uses user name : drshadow
* Management address : 172.20.0.2
* Platform : iptables
* Host OS : linux24
* Loading configuration from file E:/Ressources/firewall.fwb

Installation plan:
Copy file: E:/Ressources/firewall.fw --> /etc/fw/firewall.fw
Run script echo '--**--**--'; chmod +x /etc/fw/firewall.fw; sudo -S /etc/fw/firewall.fw && echo 'Policy activated'

Copying E:/Ressources/firewall.fw -> 172.20.0.2:/etc/fw/firewall.fw
Running command 'C:/FWbuilder/pscp.exe -load fwb_session_with_keepalive -pw XXXXXX -q E:/Ressources/firewall.fw drshadow@172.20.0.2:/etc/fw/firewall.fw'
SSH session terminated, exit status: 0
Running command 'C:/FWbuilder/plink.exe -ssh -t -load fwb_session_with_keepalive -pw XXXXXX -v -l drshadow 172.20.0.2 echo '--**--**--'; chmod +x /etc/fw/firewall.fw; sudo -S /etc/fw/firewall.fw && echo 'Policy activated''
Looking up host "172.20.0.2"
Connecting to 172.20.0.2 port 22
We claim version: SSH-2.0-PuTTY_Release_0.67
Server version: SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.1
Using SSH protocol version 2
Doing Diffie-Hellman group exchange
Doing Diffie-Hellman key exchange with hash SHA-256
Host key fingerprint is:
ssh-rsa 2048 49:33:14:bb:f2:05:b8:8d:96:18:c4:e4:04:9b:92:97
Initialised AES-256 SDCTR client->server encryption
Initialised HMAC-SHA-256 client->server MAC algorithm
Initialised AES-256 SDCTR server->client encryption
Initialised HMAC-SHA-256 server->client MAC algorithm
Using username "drshadow".
Sent password
Access granted
Opening session as main channel
Opened main channel
Allocated pty (ospeed 38400bps, ispeed 38400bps)
Started a shell/command
--**--**--
Logged in
[sudo] Mot de passe de drshadow :
Désolé, essayez de nouveau.
[sudo] Mot de passe de drshadow :
Désolé, essayez de nouveau.
[sudo] Mot de passe de drshadow :
Server sent command exit status 1
sudo: 3 saisies de mots de passe incorrectes
Disconnected: All channels closed
SSH session terminated, exit status: 1
Firewall policy installation failed

Note : a standard SSH session with putty works fine.
Any clue of what happened ?

**Comment by DrSh4d0w** [comment]
PS : for now, after compiling and uploading file, i apply it manualy with a 'chmod +x firewall_rulesV1.fw && ./firewall.fw'

so this appear to be a SSH connection issue, maybe i miss a thing in conf file ?

( more info, i try to run it with windows7 x64 and windows10 x64, same issue for both)

**Comment by sirius** [comment]
> I use the windows version ( 5.3.7-rc1 )

Can you try [5.3.7 final](https://github.com/fwbuilder/fwbuilder/releases/tag/v5.3.7)?

Windows is using the bundled pscp.exe and plink.exe, while Linux/macOS is using the system provided tools. 5.3.7 final has new versions of pscp and plink. Has this worked in a previous release?

**Comment by DrSh4d0w** [comment]
Hello,
First, thanks to your answers.
I tried with 5.3.7 final. So it works on ubuntu 14.04 but still had the same trouble on 16.04.

After further analysis, even if the version of the package ssh-server is different, the config file is still the same, with no change on the default values. (it's good to have the ssh key prompt anyway :) thx for that)

i will try localy with the linux version to see if i have the same trouble.
Maybe SSH is not the problem, but the way of the new ubuntu manage his sudo acces, i seen the encoding have changed too. So i will continue trying and keep you informed.

[fwbuilderlog_20170125.txt](https://github.com/fwbuilder/fwbuilder/files/729007/fwbuilderlog_20170125.txt)

**Comment by DrSh4d0w** [comment]
Here we are,

Tried with linux version 5.3.7 final. The result seems to be a little bit different.
Here is the verbose version of the log file.


Summary:
* Running as user : root
* Firewall name : test
* Installer uses user name : drshadow
* Management address : 127.0.0.1
* Platform : iptables
* Host OS : linux24
* Loading configuration from file /home/drshadow/test.fwb


Installation plan:
Copy file: /home/drshadow/test.fw --> /etc/fw/test.fw
Copy data file: test.fwb --> /etc/fw/
Run script echo '--**--**--'; chmod +x /etc/fw/test.fw; sudo -S /etc/fw/test.fw && echo 'Policy activated'

Copying /home/drshadow/test.fw -> 127.0.0.1:/etc/fw/test.fw
Running command '/usr/local/bin/fwbuilder -Y scp -o ConnectTimeout=30 -q /home/drshadow/test.fw drshadow@127.0.0.1:/etc/fw/test.fw'
Firewall Builder GUI 5.3.7
drshadow@127.0.0.1's password:
SSH session terminated, exit status: 0
Copying test.fwb -> 127.0.0.1:/etc/fw/
Running command '/usr/local/bin/fwbuilder -Y scp -o ConnectTimeout=30 -q /home/drshadow/test.fwb drshadow@127.0.0.1:/etc/fw/'
Firewall Builder GUI 5.3.7
drshadow@127.0.0.1's password:
SSH session terminated, exit status: 0
Running command '/usr/local/bin/fwbuilder -X ssh -o ServerAliveInterval=10 -t -t -v -l drshadow 127.0.0.1 echo '--**--**--'; chmod +x /etc/fw/test.fw; sudo -S /etc/fw/test.fw && echo 'Policy activated''
Firewall Builder GUI 5.3.7
OpenSSH_7.2p2 Ubuntu-4ubuntu2.1, OpenSSL 1.0.2g  1 Mar 2016
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: Connecting to 127.0.0.1 [127.0.0.1] port 22.
debug1: Connection established.
debug1: permanently_set_uid: 0/0
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_rsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_rsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_dsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_dsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_ecdsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_ecdsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_ed25519 type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.1
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.2p2 Ubuntu-4ubuntu2.1
debug1: match: OpenSSH_7.2p2 Ubuntu-4ubuntu2.1 pat OpenSSH* compat 0x04000000
debug1: Authenticating to 127.0.0.1:22 as 'drshadow'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256@libssh.org
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:UYU160VkxB4QjWajOMGPQvLOHcA6gAOEK5BhPhz4Pig
debug1: Host '127.0.0.1' is known and matches the ECDSA host key.
debug1: Found key in /root/.ssh/known_hosts:1
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS received
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<rsa-sha2-256,rsa-sha2-512>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey,password
debug1: Next authentication method: publickey
debug1: Trying private key: /root/.ssh/id_rsa
debug1: Trying private key: /root/.ssh/id_dsa
debug1: Trying private key: /root/.ssh/id_ecdsa
debug1: Trying private key: /root/.ssh/id_ed25519
debug1: Next authentication method: password
drshadow@127.0.0.1's password:
debug1: Authentication succeeded (password).
Authenticated to 127.0.0.1 ([127.0.0.1]:22).
debug1: channel 0: new [client-session]
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session.
debug1: pledge: network
debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
debug1: Sending environment.
debug1: Sending command: echo '--**--**--'; chmod +x /etc/fw/test.fw; sudo -S /etc/fw/test.fw && echo 'Policy activated'
Logged in
--**--**--


And the script don't run further.
Once again, SSH seems to be OK (plus, it's a different client).

i don't have any idea for now...

**Comment by DrSh4d0w** [comment]
Hello,

After some times on another project, i came back to this one.

And i have some good news.

Even if the sudo authentification fail, if i use the root account with a password set after change the line : "PermitRootLogin" to yes in the "sshd_config" file

It works !!!

So, it does not fix the issue but we can bypass the sudo authentification process.
It confirm the fact that this is not an ssh problem neither a password problem but the way of the sudo command is opperated by the system.

i'm gonna make some new try to find the cause of this sudo problem.

**Comment by DrSh4d0w** [comment]
BTW an ssh authentification with root user... :(

**Comment by sirius** [comment]
@DrSh4d0w Please reopen if you have more details.
