### ISSUE TITLE
Sry, but how to install?

### ISSUE THREAD

**Issue by starflighter** [fwbuilder/fwbuilder#29]
Sorry, for that question, but how can I install this (on a debian) system?
There are no docs about.

In the debian-repos there is only the outdatet version from sourceforge.
I would rather take this one, if I got this installed. And what are the dependencies for a successful installation?

Thanks
starflighter

**Comment by a-schild** [comment]
This is the source repository, which you can download and build your own.
Currently we don't provide packages for the different systems.

**Comment by starflighter** [comment]
yes, I know this, but how to compile? Which compiler must I use? (not GCC, or?)

**Comment by a-schild** [comment]
The usual:

```
./configure
make
sudo make install
```

Dependencies are show in the configure step
As for the compiler, the standard c++ compiler installed with debian (sudo apt-get install build-essential) get's you started.
Probably you will need more headers, like ssh/ssl stuff

**Comment by starflighter** [comment]
Thanks, but I am a little bit confused: there is no file "configure" but "configure.in" - is that the file ?

**Comment by sirius** [comment]
@starflighter `./autogen.sh` will generate and run `configure`.

You may generate a .deb too. Read [this page](https://wiki.debian.org/BuildingTutorial).
I forgot to update debian/changelog for 5.3.7, so you'll probably have to run `dch -n` before `debuild -b -uc -us`

**Comment by starflighter** [comment]
Thanks, now it works!!
