### ISSUE TITLE
DTD version in the file: 24 current: 22

### ISSUE THREAD

**Issue by ichbinder** [fwbuilder/fwbuilder#32]
Hi,
I have compiled FB in the latest version 5.3.7 but I get every time this error if I want compile a firewall:

Error: The file '/home/jakob/Dokumente/ServerUndRouter/UniArbeit/Firewall_newFB01.fwb' was created by a newer version of Firewall Builder, please upgrade in order to open this file.

DTD version in the file: 24 current: 22

My system: Linux Fedora 25

**Comment by ichbinder** [comment]
Sorry that was my false, I have to uninstall FB 5.1 first but now the FB dont find fwb_ipt:

```
Error: Failed to start program
fwb_ipt
Last error:
The process failed to start
PATH: /home/jakob/.opam/system/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/jakob/.local/bin:/home/jakob/bin
Current state of QProcess:
The process is not runn
```

I put PATH=/opt/fwbuilder/bin/:$PATH in my .bashrc but it doesnt work.

**Comment by ichbinder** [comment]
ok if I start FB direct in terminal, it works.

**Comment by sirius** [comment]
@ichbinder You want to set PATH for your DE. Check out this [page](https://wiki.archlinux.org/index.php/environment_variables).
