### ISSUE TITLE
Warnings 'const throw(FWException)' at compilation time

### ISSUE THREAD

**Issue by ffries** [fwbuilder/fwbuilder#35]
First, being an fwbuilder user since beginning of project, I would like to thank your team for picking-up fwbuilder and rebooting it.

> 
warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]

Hundreds of
> const throw(FWException)
 are reported during compilation.

This makes it impossible to read compilation log.
Shall we suppress those warnings or do you plan to change source code?

**Comment by sirius** [comment]
Hey, I'll start to modernize the code base, as I think C++11/14 is a sound default now. Suppressing warnings is not a good thing. This is a tough code base to modernize, though, with a lot of legacy code.

Track the progress in #40.

**Comment by sirius** [comment]
#45 will fix this.
