### ISSUE TITLE
Generate object config from command line

### ISSUE THREAD

**Issue by fredericve** [fwbuilder/fwbuilder#36]
I would be nice if we could generate the configuration file for a firewall object directly from the command line. That would allow you to deploy a firewall in an automated way.

The output file could be printed either to stdout, or to a file.

**Comment by sirius** [comment]
This is how fwbuilder currently works. The GUI is a visual editor for the xml-file, calling the different firewall compilers to generate output.

Compile a firewall and check the top of the output in the process log; it will show you the issued command.
