### ISSUE TITLE
is it possible to offer Releases ...

### ISSUE THREAD

**Issue by computersalat** [fwbuilder/fwbuilder#4]
... am a package maintainer at openSUSE and asking if it is possible to get a valid release (fwbuilder-5.3.6.tar.gz).
Is this project here the 'official' or 'unoffical' continuation of fwbuilder ?
... would love to see more contributions :)
great job so far :+1:

**Comment by sirius** [comment]
Hey, @cwittmer. This will be the official continuation of fwbuilder. We're currently in the process of relicensing the documentation and transfer the http://www.fwbuilder.org/ domain.

I'll check the state of the code and push a new version this week for you :)

**Comment by cwittmer** [comment]
Hey @sirius. Good news :+1: 
Thank you :)
I did on my fork for your latest 'version' a
```
git tag -a 5.3.6 -m 'version 5.3.6'  9c0cc38
```
that I can try  abuild and test ...

**Comment by roweryan** [comment]
@sirius any updates on the docs or the domain transfer?

**Comment by sirius** [comment]
We made some progress before the summer. Relicensing the docs should be no problem, but the domain transfer is a bit more difficult. The current owning entity want to transfer the domain to a non-profit organization. I agree as transferring it to a specific individual is not a good idea. However, I'm not sure that creating the "Firewall Builder Non-Profit Organization" is a correct solution.

Any ideas? What have other projects done? Is transferring it to EFF or The Linux Foundation a viable solution?

**Comment by roweryan** [comment]
I think the important thing is to get the project underway, making releases, getting users interested. That will happen here, on github. The website can come later :)

**Comment by monotek** [comment]
+1 for bringing a 5.3.7 release now and mange domain transfer + new website later.

I already added a bugreport to ubuntu to update the packages in Ubuntu with build from the new sources. 
https://bugs.launchpad.net/ubuntu/+source/fwbuilder/+bug/1571787
Seems they also waiting for a new version to pop up...

**Comment by sirius** [comment]
Ok, I'll release 5.3.7 asap - getting it in Ubuntu may result in more users/testers.

**Comment by cwittmer** [comment]
Will issue #9 be fixed in this release ?

**Comment by sirius** [comment]
@cwittmer I've added #9 to the current milestone, reflecting my plan to fix it in v5.3.7.

**Comment by monotek** [comment]
Any news about progress?
Why is RC1 not available from the Git repo?

**Comment by roweryan** [comment]
No reply? :(

**Comment by sirius** [comment]
@computersalat @monotek @roweryan 

Sorry, I have been away so long. I've cleaned up my patches and released 5.3.7, with binaries for W32 and macOS.

**Comment by computersalat** [comment]
Hi @sirius,

can you please update doc/ChangeLog for 5.3.7 Release.
Thank you

**Comment by monotek** [comment]
New 5.3.7 Ubuntu packages are available @ https://launchpad.net/~monotek/+archive/ubuntu/fwbuilder

**Comment by sirius** [comment]
@computersalat See cf77508bc3c59f634fbca25807b2fce6b8fec12f
