### ISSUE TITLE
IPv6 AddressRange

### ISSUE THREAD

**Issue by bluelineXY** [fwbuilder/fwbuilder#49]
Hi, 
an address range for IPv6 Addresses would be nice currently it's not possible to do it with the current AddressRange implementation.

**Comment by bluelineXY** [comment]
Hi, 
adding the merge request #51

**Comment by sirius** [comment]
@bluelineXY I changed my mind and implemented support for IPv6 directly in AddressRange. No need for yet another class.

Can you please check out and test: 9ac12168f00cabf25605e91a852af3d079f92e83 ?
