### ISSUE TITLE
compile error ...

### ISSUE THREAD

**Issue by computersalat** [fwbuilder/fwbuilder#5]
... running into the following compile error ...

```
[  251s] make[2]: Entering directory `/usr/src/packages/BUILD/fwbuilder-5.3.6.1/src/ipt'
[  251s] g++ -c -m64 -pipe -g -Wno-unused-parameter -D__STDC_FORMAT_MACROS -Wall -W -D_REENTRANT -DFWB_SIG=26932 -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/default -I. -I/usr/include/QtCore -I/usr/include -I.. -I../.. -I/usr/include/libxml2 -I../iptlib -I../compiler_lib -I../libfwbuilder/src -I.moc -o .obj/ipt.o ipt.cpp
[  251s] In file included from ../libfwbuilder/src/fwcompiler/PolicyCompiler.h:29:0,
[  251s]                  from ../iptlib/PolicyCompiler_ipt.h:31,
[  251s]                  from ../iptlib/CompilerDriver_ipt.h:31,
[  251s]                  from ipt.cpp:34:
[  251s] ../libfwbuilder/src/fwcompiler/Compiler.h:1007:0: warning: ignoring #pragma clang diagnostic
[  251s] ../libfwbuilder/src/fwcompiler/Compiler.h:1008:0: warning: ignoring #pragma clang diagnostic
[  251s] ../libfwbuilder/src/fwcompiler/Compiler.h:1023:0: warning: ignoring #pragma clang diagnostic
[  252s] ipt.cpp: In function 'int main(int, char**)':
[  252s] ipt.cpp:79:43: error: no matching function for call to 'QCoreApplication::QCoreApplication(int&, char**&, bool)'
[  252s] /usr/include/QtCore/qcoreapplication.h:199:5: note: candidates are: QCoreApplication::QCoreApplication(const QCoreApplication&)
[  252s] /usr/include/QtCore/qcoreapplication.h:189:5: note:                 QCoreApplication::QCoreApplication(QCoreApplicationPrivate&)
[  252s] /usr/include/QtCore/qcoreapplication.h:81:5: note:                 QCoreApplication::QCoreApplication(int&, char**)
[  252s] make[2]: *** [.obj/ipt.o] Error 1
[  252s] make[2]: Leaving directory `/usr/src/packages/BUILD/fwbuilder-5.3.6.1/src/ipt'
[  252s] make[1]: *** [sub-ipt-make_default-ordered] Error 2
[  252s] make[1]: Leaving directory `/usr/src/packages/BUILD/fwbuilder-5.3.6.1/src'
[  252s] make: *** [sub-src-make_default] Error 2
[  252s] error: Bad exit status from /var/tmp/rpm-tmp.4SwljC (%build)
[  252s] 
[  252s] 
[  252s] RPM build errors:
[  252s]     Bad exit status from /var/tmp/rpm-tmp.4SwljC (%build)
```

hopefully you can help. Perhaps I am missing something ...

**Comment by a-schild** [comment]
What platform, which QT version do you have?

**Comment by cwittmer** [comment]
I am using libqt4-4.7.1
Did dependencies change ?

**Comment by sirius** [comment]
Qt4 was end of life 19th of December 2015, so I'm not testing against Qt4 anymore. However, I don't think we have introduced any code that will not compile on both Qt4 and Qt5.

I'm targeting Qt 5.6 as it is a LTS release.

**Comment by cwittmer** [comment]
ok ... qt 4.8.5 still works ... but fwbuilder (dcc919d) crashes now on import of iptables (iptables-save) file which worked with latest version from vadim (5.1.0.3599)
```
admin@evergreen:~/firewall> fwbuilder 
Firewall Builder GUI 5.3.6
platform= "iptables" 
fwbuilder: ../libfwbuilder/src/fwbuilder/Dispatch.h:180: virtual void* libfwbuilder::Dispatch::dispatch(libfwbuilder::Interface*, void*): Zusicherung »"Call to unimplemented virtual void* Dispatch::dispatch(""Interface""*, void*)"==__null« nicht erfüllt.
Abgebrochen
```
If you want my importfile ... then just drop me a private note please. I don't want to have it 'public' here ...

**Comment by sirius** [comment]
@cwittmer I'll look into it and try to fix it before I fix #4. Your importfile would be helpful :) Please send me [by mail](mailto:sirius@bakke.co) ([PGP-key](https://pgp.mit.edu/pks/lookup?op=get&search=0xF671330AE4587835)).

**Comment by sirius** [comment]
FYI: I'm leaving for two weeks of vacation (mostly offline), so #4 and #5 will not be fixed before I'm back.

**Comment by monotek** [comment]
Any news when a new version will be ready?

**Comment by sirius** [comment]
I need feedback on a W32 build from a new toolchain (MXE). (See UNINETT/fwbuilder#2.) If it seems to be okay, I'll push all commits and release 5.3.7. This release only contains small bugfixes, mainly targeting CI and compiler compatability. 

However, using 5.3.7 as a base, I'll begin squashing reported bugs. :smiley:

**Comment by sirius** [comment]
Sorry about being away for quite some time.

5.3.7 is now released and packages scripts are updated. MXE toolchain is included in a Docker environment for W32 cross compilation.
