### ISSUE TITLE
Application Crash on adding new Objects via Menu

### ISSUE THREAD

**Issue by bluelineXY** [fwbuilder/fwbuilder#50]
Hi, 

if i try to create new Objects like New Address or New Address IPv6  the application crashes when i do it via the Menu. 

Right click on the object tree works for this objects.

**Comment by bluelineXY** [comment]
2nd commit of #51

**Comment by rephlex** [comment]
+1, I can totally reproduce the crash and the workaround described by @bluelineXY

**Comment by sirius** [comment]
Fixed by 102d68c3917950c688c1a3ca9bee42c3ff24b57f
