### ISSUE TITLE
Compile NATCompiler_ipf.cpp error: attributes at the beginning of statement are ignored gnu::fallthrough

### ISSUE THREAD

**Issue by roboshim** [fwbuilder/fwbuilder#55]
Hello,

I have tried to compile latest git code using gcc 6.4.0 on my Gentoo and since commit 302299ec52956c98f2cbf0a6a6056c3ae458925f I get following error:

    NATCompiler_ipf.cpp: In member function ‘virtual bool fwcompiler::NATCompiler_ipf::AssignInterface::processNext()’:
    NATCompiler_ipf.cpp:220:5: error: attributes at the beginning of statement are ignored [-Werror=attributes]
         [[gnu::fallthrough]];
         ^
    cc1plus: all warnings being treated as errors
    make[2]: *** [Makefile:588: .obj/NATCompiler_ipf.o] Error 1
    make[2]: *** Waiting for unfinished jobs....
    make[2]: Leaving directory '/home/GENTOO/tmp/fwbuilder-cloned/src/pflib'
    make[1]: *** [Makefile:452: sub-pflib-make_first-ordered] Error 2
    make[1]: Leaving directory '/home/GENTOO/tmp/fwbuilder-cloned/src'
    make: *** [Makefile:44: sub-src-make_first] Error 2

Until the commit 4ce388baea00372861d6743572848691ebf70e97 fwbuilder compiles without this error.

My Gentoo environment is:

    sh bash 4.4_p12
    ld GNU ld (Gentoo 2.29.1 p3) 2.29.1
    app-shells/bash:          4.4_p12::gentoo
    dev-java/java-config:     2.2.0-r3::gentoo
    dev-lang/perl:            5.24.3::gentoo
    dev-lang/python:          2.7.14-r1::gentoo, 3.4.5-r1::gentoo, 3.5.4-r1::gentoo
    dev-util/cmake:           3.9.6::gentoo
    dev-util/pkgconfig:       0.29.2::gentoo
    sys-apps/baselayout:      2.4.1-r2::gentoo
    sys-apps/openrc:          0.34.11::gentoo
    sys-apps/sandbox:         2.12::gentoo
    sys-devel/autoconf:       2.13::gentoo, 2.69-r4::gentoo
    sys-devel/automake:       1.11.6-r3::gentoo, 1.15.1-r2::gentoo
    sys-devel/binutils:       2.29.1-r1::gentoo
    sys-devel/gcc:            6.4.0-r1::gentoo
    sys-devel/gcc-config:     1.8-r1::gentoo
    sys-devel/libtool:        2.4.6-r3::gentoo
    sys-devel/make:           4.2.1::gentoo
    sys-kernel/linux-headers: 4.13::gentoo (virtual/os-headers)
    sys-libs/glibc:           2.25-r10::gentoo

Do you need more information? Do you have any idea, why fwbuilder does not compile anymore? Can you fix it?:-)

Thank you.

Regards.

Robert Wolf.

**Comment by D1W0U** [comment]
You need to add -Wno-error=attributes in the Makefile CFLAGS.
The problem is because the compiler treats some misscofing and uses the flag -Werror. So as it's a warning it treats it as error and fails.

**Comment by roboshim** [comment]
Do you mean **I should** add manually this option into Makefile or **the fwbuilder maintainer** should do it?

**Comment by D1W0U** [comment]
If you want it to compile, yesss

**Comment by D1W0U** [comment]
also would be fine if they fix it, but at moment what can you do?

**Comment by roboshim** [comment]
Oh, I understand now:-) I don't need to compile exactly the latest version:-) I need stable one and I'm OK with older commit. I just have created ebuild with version 9999 (which means latest from git) and I was surprised, that it cannot compile now on other system, even if I have successfully installed from git some earlier git revision.

So this bug report is correct and they have to fix it. OK for me. Thank you.

Regards,

Robert.

**Comment by D1W0U** [comment]
I am using latest version when cloned few days ago and I am not sure if it's working fine, because I received strange responses from unexistent IPs on my net and not sure if it's because a router or because this software.

**Comment by sirius** [comment]
It seems that only GCC >= 7 supports `-Wimplicit-fallthrough`. I've fixed the build to respect the `CXXFLAGS` environment variable. Run `CXXFLAGS=-Wno-error=attributes ./autogen.sh` in your ebuild.

If you suspect the newer version of fwbuilder to generate wrong output, then generate output with both the new and old version of fwbuilder and check if there is a significant diff.
