### ISSUE TITLE
Please make a new release

### ISSUE THREAD

**Issue by sylvestre** [fwbuilder/fwbuilder#56]
Would be great to have a new release. You have a bunch of interesting fixes.

**Comment by sirius** [comment]
I'll try to make a new one this month.

**Comment by sylvestre** [comment]
thanks!

**Comment by sirius** [comment]
@sylvestre Please try https://github.com/fwbuilder/fwbuilder/releases/tag/v6.0.0-beta

**Comment by sylvestre** [comment]
@sirius ping?

**Comment by sirius** [comment]
@sylvestre I'm cleaning up warnings, albeit a bit slowly as I have very little time for developing this projects. Patches are welcome :)

In the meantime, remove -Werror from compiler flags.

**Comment by sirius** [comment]
Please follow https://github.com/fwbuilder/fwbuilder/issues/59. I've stopped adding more features for 6.0.0 and if no other show-stoppers are appearing only documentation, changelog and packaging is remaining.
