### ISSUE TITLE
Windows-packaging fails because of missing folder w32-bin mentioned for NSIS.

### ISSUE THREAD

**Issue by ams-tschoening** [fwbuilder/fwbuilder#68]
During building for Windows I get the following error:

> Processing script file: "release/install-root/fwbuilder.nsi"
> File: "w32-bin\ci.exe" -> no files found.
> Usage: File [/nonfatal] [/a] ([/r] [/x filespec [...]] filespec [...] |
>    /oname=outfile one_file_only)
> Error in script "release/install-root/fwbuilder.nsi" on line 289 -- aborting creation process

I can't find the folder `w32-bin` anywhere and it's not mentioned in the GIT-history of the repo as well. The files are present in your released installer for Windows.

So how are things supposed to work? Should those files be removed from the NSI or do they need to be bundled? If I remove those files from the NSI, the package is created successfully.

Thanks!

**Comment by sirius** [comment]
Hi, @ams-tschoening.

You'll find the w32-bin folder here: https://github.com/fwbuilder/w32-bin

I made a new repo for the w32 binaries so I don't have to pollute the source code repo with binary files. I include the sha512 sum of all the files, and a PGP-signature of that file. Additionally, if distribution rights are revoked, for any reason, I only have to remote the w32-bin repo.

Closes #68

**Comment by ams-tschoening** [comment]
Thanks for the note. Do you clone it manually into "release/install-root"?
