### ISSUE TITLE
IPv6 'shorts' not recognized

### ISSUE THREAD

**Issue by computersalat** [fwbuilder/fwbuilder#7]
Hi,
tried to restrict 'IPv6' access ...
fwbuilder produces the following output as an example:

```
$IP6TABLES -A Cid9112X26909.0  -s xxxx:xxxx:xxxx:82::4   -j input_ext_0
```

this does not work and packets are dropped by default final DROP rule ...

I changed the IP to the **'full'** string:

```
$IP6TABLES -A Cid9112X26909.0  -s xxxx:xxxx:xxxx:0082:0000:0000:0000:0004   -j input_ext_0
```

then it works ...
using _**ip6tables v1.4.21**_

**Comment by cwittmer** [comment]
sorry for beeing loud ... it is a different problem ... at first the pings come from the original source
```
SRC=2001:4ba0:fff7:0082:0000:0000:0000:0002
DST=2607:5300:0060:39b8:0000:0000:0000:0000
```
then the SRC changes to the default GW of the destination
```
SRC=2607:5300:0060:39ff:00ff:00ff:00ff:00ff
```
this is really strange and I have no idea what is going on there ...
ipv4 ping has no problem ...

**Comment by sirius** [comment]
Keep the bugreports coming :) 

Is this related to ip6tables, not fwbuilder?

**Comment by sirius** [comment]
@computersalat I'll close this. Please reopen if it is a bug in fwbuilder, not in ip6tables.
