### ISSUE TITLE
FreeBSD port

### ISSUE THREAD

**Issue by cschuber** [fwbuilder/fwbuilder#76]
Just a heads up. I'm looking to update the FreeBSD port from the original NetCitadel version to yours. What components of qt5 do  you specifically use?

**Comment by cschuber** [comment]
Solved. FreeBSD port created.

**Comment by sirius** [comment]
@cschuber Hey! Sorry for not seeing your post before Christmas. Please notify me if you need any FreeBSD fixes upstream.
