### ISSUE TITLE
5.3.7 and 6.0.0-beta crash on new address

### ISSUE THREAD

**Issue by wirepatch** [fwbuilder/fwbuilder#81]
Steps to reproduce crash:
1. Start fwbuilder
2. Load https://cloud.mi.hdm-stuttgart.de/index.php/s/XgKJ4Rm3Z6wLakf
3. Choose »New Object« --> »New Address«.

My System: Current Ubuntu 18.04. 5.3.7 from package, 6.0.0 Beta from fresh compilation accordeing to README.md

**Comment by mgerstner** [comment]
Users of openSUSE experience this issue as well in version 5.3.7. Please refer to our [bugzilla bug](https://bugzilla.suse.com/show_bug.cgi?id=1124647) where I have posted a preliminary analysis with stacktrace and workaround (workaround is: open a context menu via right click before continuing with the other actions. Then the segfault doesn't occur).

**Comment by sirius** [comment]
@mgerstner Can you verify this fix and notify the openSUSE bugzilla?

**Comment by mgerstner** [comment]
@sirius Verification failed. It is still crashing. Even when the `lastClickedItem` is initialized to `nullptr`, the code at `src/libgui/ObjectManipulator_create_new.cpp:251` passes on the `nullptr` to `moveItems()` and the `nullptr` is subsequently dereferenced.

I have made a [preliminary patch](https://bugzilla.suse.com/attachment.cgi?id=796848&action=diff) for our package that seems to work.

**Comment by sirius** [comment]
@mgerstner Ah, 5.3.7 is missing this commit from master: https://github.com/fwbuilder/fwbuilder/commit/102d68c3917950c688c1a3ca9bee42c3ff24b57f 

I'll go over and backport some of the fixes tonight to the 5.3 branch. I probably have to make a 5.3.8 (and maybe 5.3.9) before 6.0.0 is ready.
