### ISSUE TITLE
compiling on Debian 9.8 fails error: ‘ND_SelectLibraryPage’ has not been declared

### ISSUE THREAD

**Issue by bobbisanchez** [fwbuilder/fwbuilder#85]
Hello, i try to get fwbuilder to compile under Debian 9.8 x64.
i follow the steps written in the README.md

fwbuilder:
git --git-dir .git --work-tree . describe --always --tags
v6.0.0-beta-46-g27a9ae675

[  2%] Built target fwcompiler
[  9%] Built target fwbuilder
[ 10%] Built target common
[ 12%] Built target antlr
[ 13%] Built target compilerdriver
[ 19%] Built target fwbcisco
[ 21%] Built target fwbjuniper
[ 24%] Built target fwbpf
[ 27%] Built target iptlib
[ 27%] Built target fwb_ipt
[ 28%] Built target fwb_pf
[ 28%] Built target fwb_ipf
[ 28%] Built target fwb_ipfw
[ 29%] Built target fwb_iosacl
[ 29%] Built target fwb_nxosacl
[ 29%] Built target fwb_junosacl
[ 29%] Built target fwb_pix
[ 29%] Built target fwb_procurve_acl
[ 29%] Automatic moc and uic for target gui
[ 29%] Built target gui_automoc
[ 31%] Built target import
[ 31%] Building CXX object src/libgui/CMakeFiles/gui.dir/gui_automoc.cpp.o
In file included from /mnt/Downloads/fwbuilder/build/src/libgui/gui_automoc.cpp:165:0:
/mnt/Downloads/fwbuilder/build/src/libgui/gui_automoc.dir/moc_ND_SelectLibra_BIXMIJ35S6PTZR.cpp:59:6: error: ‘ND_SelectLibraryPage’ has not been declared
 void ND_SelectLibraryPage::qt_static_metacall(QObject *_o, QMetaObject::Call _c, int _id, void **_a)
      ^~~~~~~~~~~~~~~~~~~~
/mnt/Downloads/fwbuilder/build/src/libgui/gui_automoc.dir/moc_ND_SelectLibra_BIXMIJ35S6PTZR.cpp: In function ‘void qt_static_metacall(QObject*, QMetaObject::Call, int, void**)’:
/mnt/Downloads/fwbuilder/build/src/libgui/gui_automoc.dir/moc_ND_SelectLibra_BIXMIJ35S6PTZR.cpp:64:9: error: ‘ND_SelectLibraryPage’ was not declared in this scope
         ND_SelectLibraryPage *_t = static_cast<ND_SelectLibraryPage *>(_o);
         ^~~~~~~~~~~~~~~~~~~~
/mnt/Downloads/fwbuilder/build/src/libgui/gui_automoc.dir/moc_ND_SelectLibra_BIXMIJ35S6PTZR.cpp:64:31: error: ‘_t’ was not declared in this scope
         ND_SelectLibraryPage *_t = static_cast<ND_SelectLibraryPage *>(_o);
                               ^~
/mnt/Downloads/fwbuilder/build/src/libgui/gui_automoc.dir/moc_ND_SelectLibra_BIXMIJ35S6PTZR.cpp:64:48: error: ‘ND_SelectLibraryPage’ does not name a type
         ND_SelectLibraryPage *_t = static_cast<ND_SelectLibraryPage *>(_o);
                                                ^~~~~~~~~~~~~~~~~~~~
/mnt/Downloads/fwbuilder/build/src/libgui/gui_automoc.dir/moc_ND_SelectLibra_BIXMIJ35S6PTZR.cpp:64:69: error: expected ‘>’ before ‘*’ token
         ND_SelectLibraryPage *_t = static_cast<ND_SelectLibraryPage *>(_o);
                                                                     ^
/mnt/Downloads/fwbuilder/build/src/libgui/gui_automoc.dir/moc_ND_SelectLibra_BIXMIJ35S6PTZR.cpp:64:69: error: expected ‘(’ before ‘*’ token
/mnt/Downloads/fwbuilder/build/src/libgui/gui_automoc.dir/moc_ND_SelectLibra_BIXMIJ35S6PTZR.cpp:64:70: error: expected primary-expression before ‘>’ token
         ND_SelectLibraryPage *_t = static_cast<ND_SelectLibraryPage *>(_o);
                                                                      ^
/mnt/Downloads/fwbuilder/build/src/libgui/gui_automoc.dir/moc_ND_SelectLibra_BIXMIJ35S6PTZR.cpp:64:75: error: expected ‘)’ before ‘;’ token
         ND_SelectLibraryPage *_t = static_cast<ND_SelectLibraryPage *>(_o);
                                                                           ^
/mnt/Downloads/fwbuilder/build/src/libgui/gui_automoc.dir/moc_ND_SelectLibra_BIXMIJ35S6PTZR.cpp:72:9: error: ‘ND_SelectLibraryPage’ was not declared in this scope
         ND_SelectLibraryPage *_t = static_cast<ND_SelectLibraryPage *>(_o);
         ^~~~~~~~~~~~~~~~~~~~
/mnt/Downloads/fwbuilder/build/src/libgui/gui_automoc.dir/moc_ND_SelectLibra_BIXMIJ35S6PTZR.cpp:72:31: error: ‘_t’ was not declared in this scope
         ND_SelectLibraryPage *_t = static_cast<ND_SelectLibraryPage *>(_o);
                               ^~
/mnt/Downloads/fwbuilder/build/src/libgui/gui_automoc.dir/moc_ND_SelectLibra_BIXMIJ35S6PTZR.cpp:72:48: error: ‘ND_SelectLibraryPage’ does not name a type
         ND_SelectLibraryPage *_t = static_cast<ND_SelectLibraryPage *>(_o);
                                                ^~~~~~~~~~~~~~~~~~~~
/mnt/Downloads/fwbuilder/build/src/libgui/gui_automoc.dir/moc_ND_SelectLibra_BIXMIJ35S6PTZR.cpp:72:69: error: expected ‘>’ before ‘*’ token
         ND_SelectLibraryPage *_t = static_cast<ND_SelectLibraryPage *>(_o);
                                                                     ^
/mnt/Downloads/fwbuilder/build/src/libgui/gui_automoc.dir/moc_ND_SelectLibra_BIXMIJ35S6PTZR.cpp:72:69: error: expected ‘(’ before ‘*’ token
/mnt/Downloads/fwbuilder/build/src/libgui/gui_automoc.dir/moc_ND_SelectLibra_BIXMIJ35S6PTZR.cpp:72:70: error: expected primary-expression before ‘>’ token
         ND_SelectLibraryPage *_t = static_cast<ND_SelectLibraryPage *>(_o);
                                                                      ^
/mnt/Downloads/fwbuilder/build/src/libgui/gui_automoc.dir/moc_ND_SelectLibra_BIXMIJ35S6PTZR.cpp:72:75: error: expected ‘)’ before ‘;’ token
         ND_SelectLibraryPage *_t = static_cast<ND_SelectLibraryPage *>(_o);
                                                                           ^
/mnt/Downloads/fwbuilder/build/src/libgui/gui_automoc.dir/moc_ND_SelectLibra_BIXMIJ35S6PTZR.cpp: At global scope:
/mnt/Downloads/fwbuilder/build/src/libgui/gui_automoc.dir/moc_ND_SelectLibra_BIXMIJ35S6PTZR.cpp:88:19: error: ‘ND_SelectLibraryPage’ has not been declared
 const QMetaObject ND_SelectLibraryPage::staticMetaObject = {
                   ^~~~~~~~~~~~~~~~~~~~
/mnt/Downloads/fwbuilder/build/src/libgui/gui_automoc.dir/moc_ND_SelectLibra_BIXMIJ35S6PTZR.cpp:94:20: error: ‘ND_SelectLibraryPage’ has not been declared
 const QMetaObject *ND_SelectLibraryPage::metaObject() const
                    ^~~~~~~~~~~~~~~~~~~~
/mnt/Downloads/fwbuilder/build/src/libgui/gui_automoc.dir/moc_ND_SelectLibra_BIXMIJ35S6PTZR.cpp:94:55: error: non-member function ‘const QMetaObject* metaObject()’ cannot have cv-qualifier
 const QMetaObject *ND_SelectLibraryPage::metaObject() const
                                                       ^~~~~
/mnt/Downloads/fwbuilder/build/src/libgui/gui_automoc.dir/moc_ND_SelectLibra_BIXMIJ35S6PTZR.cpp: In function ‘const QMetaObject* metaObject()’:
/mnt/Downloads/fwbuilder/build/src/libgui/gui_automoc.dir/moc_ND_SelectLibra_BIXMIJ35S6PTZR.cpp:96:21: error: ‘QScopedPointer<QObjectData> QObject::d_ptr’ is protected within this context
     return QObject::d_ptr->metaObject ? QObject::d_ptr->dynamicMetaObject() : &staticMetaObject;
                     ^~~~~
In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/qvariant.h:51:0,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/QVariant:1,
                 from /mnt/Downloads/fwbuilder/build/src/libgui/ui_actionsdialog_q.h:12,
                 from /mnt/Downloads/fwbuilder/build/src/libgui/gui_automoc.dir/../../../../fwbuilder/src/libgui/ActionsDialog.h:30,
                 from /mnt/Downloads/fwbuilder/build/src/libgui/gui_automoc.dir/moc_ActionsDialog_3VZX2REKHQIUUX.cpp:9,
                 from /mnt/Downloads/fwbuilder/build/src/libgui/gui_automoc.cpp:2:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h:419:33: note: declared protected here
     QScopedPointer<QObjectData> d_ptr;
                                 ^~~~~
In file included from /mnt/Downloads/fwbuilder/build/src/libgui/gui_automoc.cpp:165:0:
/mnt/Downloads/fwbuilder/build/src/libgui/gui_automoc.dir/moc_ND_SelectLibra_BIXMIJ35S6PTZR.cpp:96:21: error: invalid use of non-static data member ‘QObject::d_ptr’
     return QObject::d_ptr->metaObject ? QObject::d_ptr->dynamicMetaObject() : &staticMetaObject;
                     ^~~~~
In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/qvariant.h:51:0,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/QVariant:1,
                 from /mnt/Downloads/fwbuilder/build/src/libgui/ui_actionsdialog_q.h:12,
                 from /mnt/Downloads/fwbuilder/build/src/libgui/gui_automoc.dir/../../../../fwbuilder/src/libgui/ActionsDialog.h:30,
                 from /mnt/Downloads/fwbuilder/build/src/libgui/gui_automoc.dir/moc_ActionsDialog_3VZX2REKHQIUUX.cpp:9,
                 from /mnt/Downloads/fwbuilder/build/src/libgui/gui_automoc.cpp:2:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h:419:33: note: declared here
     QScopedPointer<QObjectData> d_ptr;
                                 ^~~~~
In file included from /mnt/Downloads/fwbuilder/build/src/libgui/gui_automoc.cpp:165:0:
/mnt/Downloads/fwbuilder/build/src/libgui/gui_automoc.dir/moc_ND_SelectLibra_BIXMIJ35S6PTZR.cpp:96:50: error: ‘QScopedPointer<QObjectData> QObject::d_ptr’ is protected within this context
     return QObject::d_ptr->metaObject ? QObject::d_ptr->dynamicMetaObject() : &staticMetaObject;
                                                  ^~~~~
In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/qvariant.h:51:0,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/QVariant:1,
                 from /mnt/Downloads/fwbuilder/build/src/libgui/ui_actionsdialog_q.h:12,
                 from /mnt/Downloads/fwbuilder/build/src/libgui/gui_automoc.dir/../../../../fwbuilder/src/libgui/ActionsDialog.h:30,
                 from /mnt/Downloads/fwbuilder/build/src/libgui/gui_automoc.dir/moc_ActionsDialog_3VZX2REKHQIUUX.cpp:9,
                 from /mnt/Downloads/fwbuilder/build/src/libgui/gui_automoc.cpp:2:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h:419:33: note: declared protected here
     QScopedPointer<QObjectData> d_ptr;
                                 ^~~~~
In file included from /mnt/Downloads/fwbuilder/build/src/libgui/gui_automoc.cpp:165:0:
/mnt/Downloads/fwbuilder/build/src/libgui/gui_automoc.dir/moc_ND_SelectLibra_BIXMIJ35S6PTZR.cpp:96:50: error: invalid use of non-static data member ‘QObject::d_ptr’
     return QObject::d_ptr->metaObject ? QObject::d_ptr->dynamicMetaObject() : &staticMetaObject;
                                                  ^~~~~
In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/qvariant.h:51:0,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/QVariant:1,
                 from /mnt/Downloads/fwbuilder/build/src/libgui/ui_actionsdialog_q.h:12,
                 from /mnt/Downloads/fwbuilder/build/src/libgui/gui_automoc.dir/../../../../fwbuilder/src/libgui/ActionsDialog.h:30,
                 from /mnt/Downloads/fwbuilder/build/src/libgui/gui_automoc.dir/moc_ActionsDialog_3VZX2REKHQIUUX.cpp:9,
                 from /mnt/Downloads/fwbuilder/build/src/libgui/gui_automoc.cpp:2:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h:419:33: note: declared here
     QScopedPointer<QObjectData> d_ptr;
                                 ^~~~~
In file included from /mnt/Downloads/fwbuilder/build/src/libgui/gui_automoc.cpp:165:0:
/mnt/Downloads/fwbuilder/build/src/libgui/gui_automoc.dir/moc_ND_SelectLibra_BIXMIJ35S6PTZR.cpp: At global scope:
/mnt/Downloads/fwbuilder/build/src/libgui/gui_automoc.dir/moc_ND_SelectLibra_BIXMIJ35S6PTZR.cpp:99:7: error: ‘ND_SelectLibraryPage’ has not been declared
 void *ND_SelectLibraryPage::qt_metacast(const char *_clname)
       ^~~~~~~~~~~~~~~~~~~~
/mnt/Downloads/fwbuilder/build/src/libgui/gui_automoc.dir/moc_ND_SelectLibra_BIXMIJ35S6PTZR.cpp: In function ‘void* qt_metacast(const char*)’:
/mnt/Downloads/fwbuilder/build/src/libgui/gui_automoc.dir/moc_ND_SelectLibra_BIXMIJ35S6PTZR.cpp:103:47: error: ‘ND_SelectLibraryPage’ does not name a type
         return static_cast<void*>(const_cast< ND_SelectLibraryPage*>(this));
                                               ^~~~~~~~~~~~~~~~~~~~
/mnt/Downloads/fwbuilder/build/src/libgui/gui_automoc.dir/moc_ND_SelectLibra_BIXMIJ35S6PTZR.cpp:103:67: error: expected ‘>’ before ‘*’ token
         return static_cast<void*>(const_cast< ND_SelectLibraryPage*>(this));
                                                                   ^
/mnt/Downloads/fwbuilder/build/src/libgui/gui_automoc.dir/moc_ND_SelectLibra_BIXMIJ35S6PTZR.cpp:103:67: error: expected ‘(’ before ‘*’ token
/mnt/Downloads/fwbuilder/build/src/libgui/gui_automoc.dir/moc_ND_SelectLibra_BIXMIJ35S6PTZR.cpp:103:68: error: expected primary-expression before ‘>’ token
         return static_cast<void*>(const_cast< ND_SelectLibraryPage*>(this));
                                                                    ^
/mnt/Downloads/fwbuilder/build/src/libgui/gui_automoc.dir/moc_ND_SelectLibra_BIXMIJ35S6PTZR.cpp:103:70: error: invalid use of ‘this’ in non-member function
         return static_cast<void*>(const_cast< ND_SelectLibraryPage*>(this));
                                                                      ^~~~
/mnt/Downloads/fwbuilder/build/src/libgui/gui_automoc.dir/moc_ND_SelectLibra_BIXMIJ35S6PTZR.cpp:103:76: error: expected ‘)’ before ‘;’ token
         return static_cast<void*>(const_cast< ND_SelectLibraryPage*>(this));
                                                                            ^
/mnt/Downloads/fwbuilder/build/src/libgui/gui_automoc.dir/moc_ND_SelectLibra_BIXMIJ35S6PTZR.cpp:104:44: error: cannot call member function ‘virtual void* QWizardPage::qt_metacast(const char*)’ without object
     return QWizardPage::qt_metacast(_clname);
                                            ^
/mnt/Downloads/fwbuilder/build/src/libgui/gui_automoc.dir/moc_ND_SelectLibra_BIXMIJ35S6PTZR.cpp: At global scope:
/mnt/Downloads/fwbuilder/build/src/libgui/gui_automoc.dir/moc_ND_SelectLibra_BIXMIJ35S6PTZR.cpp:107:5: error: ‘ND_SelectLibraryPage’ has not been declared
 int ND_SelectLibraryPage::qt_metacall(QMetaObject::Call _c, int _id, void **_a)
     ^~~~~~~~~~~~~~~~~~~~
/mnt/Downloads/fwbuilder/build/src/libgui/gui_automoc.dir/moc_ND_SelectLibra_BIXMIJ35S6PTZR.cpp: In function ‘int qt_metacall(QMetaObject::Call, int, void**)’:
/mnt/Downloads/fwbuilder/build/src/libgui/gui_automoc.dir/moc_ND_SelectLibra_BIXMIJ35S6PTZR.cpp:109:47: error: cannot call member function ‘virtual int QWizardPage::qt_metacall(QMetaObject::Call, int, void**)’ without object
     _id = QWizardPage::qt_metacall(_c, _id, _a);
                                               ^
/mnt/Downloads/fwbuilder/build/src/libgui/gui_automoc.dir/moc_ND_SelectLibra_BIXMIJ35S6PTZR.cpp:116:28: error: invalid use of ‘this’ in non-member function
         qt_static_metacall(this, _c, _id, _a);
                            ^~~~
src/libgui/CMakeFiles/gui.dir/build.make:11091: die Regel für Ziel „src/libgui/CMakeFiles/gui.dir/gui_automoc.cpp.o“ scheiterte
make[2]: *** [src/libgui/CMakeFiles/gui.dir/gui_automoc.cpp.o] Fehler 1
make[2]: Das Ziel „src/libgui/CMakeFiles/gui.dir/build“ wurde wegen Fehlern nicht aktualisiert.
CMakeFiles/Makefile2:1126: die Regel für Ziel „src/libgui/CMakeFiles/gui.dir/all“ scheiterte
make[1]: *** [src/libgui/CMakeFiles/gui.dir/all] Fehler 2
Scanning dependencies of target fwbparser
[ 31%] Building CXX object src/parsers/CMakeFiles/fwbparser.dir/IOSCfgLexer.cpp.o

**Comment by sirius** [comment]
Fixed in fe8be2e61d8f53302ef2502538163557c0917ced
