### ISSUE TITLE
fwbuilder.org is not accessible.

### ISSUE THREAD

**Issue by nikmartin** [fwbuilder/fwbuilder#89]

**Comment by sirius** [comment]
Sorry, I don't own the domain fwbuilder.org, and it is currently not for sale.

**Comment by nikmartin** [comment]
So why do you link to it from the github repo? It's linked to here: https://github.com/fwbuilder/fwbuilder

**Comment by sirius** [comment]
Because this is a clone of the project, and all the official documentation is there (or rather on http://fwbuilder.sourceforge.net). However, I can adjust the url in the readme.
