### ISSUE TITLE
Request, iptables and newer version

### ISSUE THREAD

**Issue by thefiredragon** [fwbuilder/fwbuilder#92]
Hello,
I have a little question, will you make a new build from fwbuilder? Since the last release there are many commits.

Also I noticed under debian buster iptables know old syntax, so iptables bring up the information that some ipables-legacy rules are present after using fwbuilder with debian buster eg. newer versions of iptables.

Do I need something to know here? 
best regards

**Comment by thefiredragon** [comment]
https://wiki.debian.org/nftables

**Comment by gurubert** [comment]
See issue https://github.com/fwbuilder/fwbuilder/issues/88#issuecomment-538328233

Best would be to have an nftables compiler for fwbuilder as requested in issue https://github.com/fwbuilder/fwbuilder/issues/17

**Comment by sirius** [comment]
I'm triaging bugs now, deciding if I'm going to release the current code as 6.0.

Any patches - if needed - for maintaining iptables support on Debian are very much welcome.
