### ISSUE TITLE
configuring iptables seems quite cumbersome

### ISSUE THREAD

**Issue by Tcll** [fwbuilder/fwbuilder#95]
the interface seems to expect I work with a LAN-based firewall, which I don't have...

all I want to do is configure iptables locally without using the terminal, as `/etc/hosts` doesn't seem to work properly, nor can it block IP ranges without an extensive amount of work.
(I don't expect to use ssh because it's an insecurity)

is this even possible??

**Comment by sirius** [comment]
Firewall Builder simply translate firewall rules into different formats - for multiple plattforms and firewall applications. One of those is iptables, which you may run locally on your computer.

I suggest you read your distro's documentation for firewalls. You may use fwbuilder to generate the iptables rules, and then use some other gui to enable them - if you do not wish to use the terminal.
