### ISSUE TITLE
Can't add VLAN interface

### ISSUE THREAD

**Issue by tblancher** [fwbuilder/fwbuilder#97]
I have a primary Ethernet interface enp4s0, with a VLAN interface of enp4s0.66.  When I add a subinterface and try to name it 'enp4s0.66', I get the following error message:

> 'enp4s0.66' looks like a name of a vlan interface but it does not match the name of the parent 
> interface 'enp4s0'

I'm using fwbuilder 5.3.7 on Arch Linux, trying to configure a Debian 10 (buster) firewall using iptables (I am not using the nftables shim).

**Comment by sirius** [comment]
Hey, @tblancher 

This is fixed now - see https://github.com/fwbuilder/fwbuilder/commit/be1306c8229ae981c4be76ba37a46cf903829792
